# Generated by Django 4.0.4 on 2022-09-02 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0004_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commentapp.comment'),
        ),
        migrations.DeleteModel(
            name='reply',
        ),
    ]
