# Generated by Django 4.0.4 on 2022-08-03 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('articleapp', '0003_alter_article_options_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
        migrations.AddField(
            model_name='article',
            name='liked_user',
            field=models.ManyToManyField(related_name='like', through='articleapp.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
